# Generated by Django 4.2.4 on 2023-08-23 11:49

from django.conf import settings
from django.db import migrations, models
import nw_workspaces.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('github_repo_url', models.CharField(max_length=200)),
                ('github_ssh_key_file', models.FileField(upload_to=nw_workspaces.models.upload_to_workspace)),
                ('admin_username', models.CharField(max_length=50)),
                ('env_file', models.FileField(upload_to='env_files/')),
                ('cloudflare_bearer_token', models.CharField(max_length=200)),
                ('cloudflare_zone_id', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
