# Generated by Django 4.2.4 on 2023-08-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='app_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
