# Generated by Django 4.2.4 on 2023-08-26 13:20

from django.db import migrations, models
import nw_workspaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_workspaces', '0002_workspace_app_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='docker_start_command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='env_file',
            field=models.FileField(upload_to=nw_workspaces.models.upload_to_workspace),
        ),
    ]
